version: '3.7'

services:
  nginx:
    image: nginx
    #ports:
    # - 80:80
    volumes:
      - /home/ee/hugo/bibledolls/public:/usr/share/nginx/html:ro
    networks:
      - net
    deploy:
      labels:
        - traefik.enable=true
        - traefik.nginx.port=80
        - traefik.frontend.entryPoints.http.redirect=https
        - traefik.frontend.rule=Host:bibledolls.com

networks:
  net:
    external: true
